# Generated by Django 5.0 on 2026-01-07 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_alter_snippet_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='highligted',
            new_name='highlighted',
        ),
    ]
